### ISSUE TITLE
[Bug] Circle battery issues

### ISSUE THREAD

**Issue by superbats** [siavash79/PixelXpert#780]
### Describe the issue

Colour stays red.  Circle battery resizes itself to a tiny version at random.

### Steps to reproduce

In status bar changes, select dashed circle battery, resize to 110%.

Battery colour always stays red.
Battery will resize itself at random.

### Expected behavior

White circle battery, size stays fixed.

### Your device setup (Please take some time to give correct information here)

Pixel 8 Pro
A14 Stock firmware, January update

![Screenshot_20240110-153027](https://github.com/siavash79/PixelXpert/assets/155029056/b68c794a-8935-4ea3-801f-22495a1bdd88)

### Logs

[LSPosed_2024-01-10T15_32_26.010200.zip](https://github.com/siavash79/PixelXpert/files/13893809/LSPosed_2024-01-10T15_32_26.010200.zip)

**Comment by superbats** [comment]
Apparently, the battery resizes itself whenever the phone is charged.

**Comment by siavash79** [comment]
about the battery remaining "red": are we sure the battery color options and ranges configured correctly? can you please post a screenshot?

**Comment by superbats** [comment]
![Screenshot_20240115-083313](https://github.com/siavash79/PixelXpert/assets/155029056/456dc7ee-0e2a-4788-bb72-69a8c8f1d3d0)
![Screenshot_20240115-083321](https://github.com/siavash79/PixelXpert/assets/155029056/8fc278e7-54e7-4fe1-9279-0c43ac07657f)

**Comment by kaoneko** [comment]
I know non-Pixel ROMs are not supported, but this information may be relevant. If not, just ignore me.

I use LineageOS 20 (Android 13) with the circle battery indicator selected in LineageOS' own settings. I don't use any battery icon customization in Pixel Xpert.

When I upgraded from canary-320 (_fixed occasional statusbar layout glitches_) to canary-321 (_fixed occasional statusbar layout glitches (agian!)_) I noticed my battery icon was like 50% of its usual size. I hadn't experienced any statusbar layout glitches before.

At that time I reverted back to the latest stable, v3.2.0. Today I upgraded to v3.3.0 and got the tiny battery icon again.

- On the lockscreen the battery icon is never tiny
- When I switch the battery style from _Circle_ to _Icon portrait_ **in LineageOS settings** the _Icon portrait_ icon is regular size
- When I switch the battery style from _Icon portrait_ to _Circle_ **in LineageOS settings** the regular sized _Circle_ icon is shown for 1 second and then replaced with the tiny version
- I've observed it spontaneously being regular size again at one point when I picked up my phone, in the hour or so since I installed v3.3.0
- When I connected my charger, the tiny circular icon was replaced with a regular sized charging _Circle_ icon, then when I disconnected my charger the now discharging icon was at regular size too. So connecting the charger in my case helps with restoring the size of the circular battery icon.
- LineageOS' circular icon usually becomes red at 15%. My battery is now at 50% and the icon is not red.

Again, I don't use any battery icon customization in Pixel Xpert, but this still happens.

I know non-Pixel ROMs are not supported, but maybe this information will help.

**Comment by RealFakeGitter** [comment]
On the pixel 7 pro same behavior when I plug in the charger the size changes regardless of what the settings say. When I unplug it its the same in my case the battery icon gets tiny and unreadble. If I move the size indicator in pixel xpert settings even a notch it goes back to the expected size but on next plugin the problem repeats . 
I am on STOCK pixel 7 pro A14

**Comment by EleoXDA** [comment]
@superbats @RealFakeGitter @kaoneko should be fixed with latest stable

**Comment by kaoneko** [comment]
Yes, fixed for me. Thank you!

**Comment by RealFakeGitter** [comment]
> @superbats @RealFakeGitter @kaoneko should be fixed with latest stable

Yupp it works. It was actually fixed in the beta which I switched to right after posting this

**Comment by superbats** [comment]
It worked briefly for me.  Was white, then when it went red (no yellow
warning colour) then it stayed red even after charging.

**Comment by siavash79** [comment]
That red color corresponds to power saving mode. Are you sure power saving is disabled?

**Comment by superbats** [comment]
Okay, you're right, that red colour was for power saving mode.
