### ISSUE TITLE
[Bug] Option to close the QS panel with a single swipe is missing

### ISSUE THREAD

**Issue by kaoneko** [siavash79/PixelXpert#784]
### Describe the issue

The v3.3.0 changelog says this option was added, but it's not listed anywhere. Searching for "close" also doesn't provide any results.

### Steps to reproduce

1. Open v3.3.0 and try to find it
2. You can't, or I'm stupid

### Your device setup (Please take some time to give correct information here)

I'm on an unsupported Android 13 based ROM, but I just want to know if the option should be there, or if the changelog is mistaken.

**Comment by kaoneko** [comment]
@EleoXDA Is this your way of saying it was written in the changelog by mistake?

**Comment by EleoXDA** [comment]
I am saying it is shown only if you enable quick pull DOWN

**Comment by kaoneko** [comment]
Thanks for clearing that up. Then it's probably a custom ROM issue, sorry for bothering you.

**Comment by dttzyjw0012** [comment]
I build my own PixelXpert version which I named it AospXpert for Android 12+ AOSP roms. yes, this is not for the GoogleOS(which I call the Google Pixel device's stock rom). So if u want to use my mod, pls go to my project: https://github.com/dttzyjw0012/AospXpert. And do not reply in this issus, i know the PixelXpert team do not to want to be disturbed.

to PixelXpert team: i reply this because i can not @ this issus auther or participants in my issus: https://github.com/siavash79/PixelXpert/issues/980 , but there are just 10 issus i will reply just like this, so i wish this would not disturb you, thx.
