### ISSUE TITLE
Remove empty bottom space between keyboard and hide/change keyboard buttons

### ISSUE THREAD

**Issue by gygabyte017** [siavash79/PixelXpert#822]
What's on your mind?
Hi, I noticed that there is an empty space when the keyboard is open between the keyboard bottom edge (i.e. below the space bar) and the bottom bar where there is the arrow and the keyboard small buttons to hide or change the keyboard. I would love to customize that margin in order to shrink it or remove it completely.

Is this feature implemented on any other app/mod/rom? please specify
Yes, I remember this setting is implemented for example in EvolutionX roms.

**Comment by EleoXDA** [comment]
That is called navbar soace and if you remove it many apps malfunction. You bave an option to remove it on other mods like Iconify. But since it is buggy with some apps, it will NOT be implemented in PixelXpert, to avoid bugreports saying apps don't function ok with that feature enabled. This is tested inside team and evaluated accordingly.

To avoid multiple similar feature requests, PLEASE search through denied requests before making a new one. This will save both your and our time, as I remember this to be denied several times already in here.
