### ISSUE TITLE
Ability to turn off some options

### ISSUE THREAD

**Issue by r0ddty** [siavash79/PixelXpert#833]
What's on your mind?
The ability to turn off customization for whole categories(like statusbar), because sometimes it makes weird things with some roms, for example removing space between clock and chip edge:
before installing PixelXpert:
![image](https://github.com/siavash79/PixelXpert/assets/148452073/733cd9e4-801c-4084-931d-c0b7dff1f869)
after installing PixelXpert: 
![image](https://github.com/siavash79/PixelXpert/assets/148452073/7212ab53-9593-4f04-9b05-37c9d8be402f)

Is this feature implemented on any other app/mod/rom? please specify
i dont actually know

**Comment by EleoXDA** [comment]
We do not and will **never** support any custom ROMs. Fork repo, turn off options, compile, use

**Comment by dttzyjw0012** [comment]
I build my own PixelXpert version which I named it AospXpert for Android 12+ AOSP roms. yes, this is not for the GoogleOS(which I call the Google Pixel device's stock rom). So if u want to use my mod, pls go to my project: https://github.com/dttzyjw0012/AospXpert. And do not reply in this issus, i know the PixelXpert team do not to want to be disturbed.

to PixelXpert team: i reply this because i can not @ this issus auther or participants in my issus: https://github.com/siavash79/PixelXpert/issues/980 , but there are just 10 issus i will reply just like this, so i wish this would not disturb you, thx.
