### ISSUE TITLE
Add to fdroid

### ISSUE THREAD

**Issue by Thewisem** [siavash79/PixelXpert#839]
What's on your mind?
Add this app to fdroid store
Fdroid is a store meant for free and open source software enthusiast which do not want to use propietary software. I think this would be a good addition to the store

Is this feature implemented on any other app/mod/rom? please specify
Magisk

**Comment by EleoXDA** [comment]
We do not want this app to be installed as a mainstream, simple and available app.

This is an xposed module. It should be found and used by people who are active in XDA developers, 4PDA or similar development forums. 

So, no. As the target audience is only Pixel stock firmware users who seek to tweak their device, and not any other custom ROM/vendor ROM users, I think it is better to be not available to masses.

Or else we will see 100x the reports from people who didn't even read instructions before installing.

**Comment by EleoXDA** [comment]
And also, we have precompiled lib that fdroid doesn't allow, so even if we submit, it won't be approved

**Comment by mpeter50** [comment]
> And also, we have precompiled lib that fdroid doesn't allow, so even if we submit, it won't be approved

What precompiled lib do you use? I was considering installing this module anyway, but I dont like this.
Also, that may have issues with your license, GPL v3: https://www.gnu.org/licenses/gpl-faq.en.html#FSWithNFLibs
Please, at least consider mentioning your use of a precompiled (propriertary?) library in the readme, as the GPL wishes.

Personally I dont think having Xposed modules on F-droid has any dangers, because the user would need to have the Xposed framework being installed too, and thats not really a simple thing to do. There is a few dozen of them over there already, and also, in my experience it is much easier to brick the OS by installing Xposed and such than with installing an Xposed module like this, because if a function does not exist that the module would hook, or its signature has changed, the module will just crash and rarely bring down the processes it is being executed in. It is Xposed that does risky modifications to system files.

However, having app on F-droid main also means to me as a user, that it is free of shady things such as precompiled libraries which cannot be inspected for what are they doing, because they have automated tools to check for it. But I also dont see what use would a 3rd party proprietary lib would have in an xposed module?
At that point I'll probably just make my own module as in the old days. The only complicated part is just finding which method to hook, and its way easier with FOSS ROMs than with overcustomized manufacturer garbage, like those that you understandably do not support.

**Comment by EleoXDA** [comment]
> the module will just crash and rarely bring down the processes it is being executed in

R u sure? Please check what is hooked to module in xposed.

> But I also dont see what use would a 3rd party proprietary lib would have in an xposed module?

Google's in-device AI engine used in Depth wallpaper
