### ISSUE TITLE
The Padding of statusbar

### ISSUE THREAD

**Issue by murikbmx** [siavash79/PixelXpert#840]
Possible to add the padding of the statusbar start/end?
status_bar_padding_start
status_bar_padding_end
On my PE the padding is huge, would be great to reduce them

**Comment by EleoXDA** [comment]
Good to know. Report to PE devs

**Comment by dttzyjw0012** [comment]
I build my own PixelXpert version which I named it AospXpert for Android 12+ AOSP roms. yes, this is not for the GoogleOS(which I call the Google Pixel device's stock rom). So if u want to use my mod, pls go to my project: https://github.com/dttzyjw0012/AospXpert. And do not reply in this issus, i know the PixelXpert team do not to want to be disturbed.

to PixelXpert team: i reply this because i can not @ this issus auther or participants in my issus: https://github.com/siavash79/PixelXpert/issues/980 , but there are just 10 issus i will reply just like this, so i wish this would not disturb you, thx.
