### ISSUE TITLE
Dashed Battery Circle getting themed[Bug] 

### ISSUE THREAD

**Issue by Zaxx420** [siavash79/PixelXpert#854]
### Describe the issue

Instead of red/yellow/green the circle matches primary wallpaper color.

### Steps to reproduce

In barr icon settings select dashed circle and 'Make it colorful'.

### Expected behavior

Entire circle color same as primary wallpaper color in use.

### Your device setup (Please take some time to give correct information here)

P6a on Latest Stock A14 June update, Magisk 27.0, Lsposed 1.8.6

**Comment by EleoXDA** [comment]
Your issue description is: "Instead of red/yellow/green the circle matches primary wallpaper color" and expected behavior is "Entire circle color same as primary wallpaper color in use". This means issue is resolved? If not, please make it more clear what is the issue and what you expected to see instead please.

One more thing, please read:
https://github.com/siavash79/PixelXpert/issues/853#issuecomment-2171870674
