### ISSUE TITLE
Volume button not working only while installing.

### ISSUE THREAD

**Issue by aka5hh** [siavash79/PixelXpert#878]
### Describe the issue

Volume button not working only while installing pixel expert in ksu.

### Steps to reproduce

Click install modules 
Selected Pixel expert 
Then I'm stuck 

### Expected behavior

I would press the volume up button to continue with the installation 

### Your device setup (Please take some time to give correct information here)

Mi 11x
Pixel OS 
Android 14 QPR3
![Screenshot_20240829-005249](https://github.com/user-attachments/assets/5fd29ba0-bebe-435b-ba39-19ca7271a19e)

### Logs

I couldn't install pixel expert

**Comment by berkantdu123** [comment]
Same issue on Evolution X

**Comment by EleoXDA** [comment]
ONLY STOCK PIXEL FIRMWARE IN GOOGLE PIXEL DEVICES IS SUPPORTED!! READ README FILE!

**Comment by aka5hh** [comment]
It worked. I unzipped, then installed the apk, then gave it root permission, then flashed the zip. It works that way.

**Comment by EleoXDA** [comment]
Good. But do not report if anything does not work. Your setup is not supported

**Comment by dttzyjw0012** [comment]
I build my own PixelXpert version which I named it AospXpert for Android 12+ AOSP roms. yes, this is not for the GoogleOS(which I call the Google Pixel device's stock rom). So if u want to use my mod, pls go to my project: https://github.com/dttzyjw0012/AospXpert. And do not reply in this issus, i know the PixelXpert team do not to want to be disturbed.

to PixelXpert team: i reply this because i can not @ this issus auther or participants in my issus: https://github.com/siavash79/PixelXpert/issues/980 , but there are just 10 issus i will reply just like this, so i wish this would not disturb you, thx.
