### ISSUE TITLE
[Bug] [Force aod on charging]: Correct transition animation 

### ISSUE THREAD

**Issue by Nakamerica** [siavash79/PixelXpert#923]
### Describe the issue

Forcing the always on display during charging does not follow the same transition animations that the always on display otherwise shows when enabled all the time from device settings. 

### Steps to reproduce

1. Enable the Always show time and info toggle in device settings
2. Unlock the device using fingerprint animation/turn on the display using the power button
3. Notice the animation of the display emerging from the fingerprint unlock icon/power button

As compared to:
1. Turn on Force Aod while charging toggle from PixelXpert
2. Repeat Step 2 from above. 
3. The natural animation is not reproduced.  

### Expected behavior

Transition animation of the display emerging from the fingerprint unlock icon/power button

### Your device setup (Please take some time to give correct information here)

- Google Pixel 6 Pro running the September patch of HelluvaOS. 
- 15
- September patch
- KSu version 11928
- PixelXpert
- Zygisk: Lsposed version 1.9.3_mod (7244)

**Comment by EleoXDA** [comment]
> * Google Pixel 6 Pro running the September patch of HelluvaOS

Read README!

**Comment by Nakamerica** [comment]
my apologies.

**Comment by dttzyjw0012** [comment]
I build my own PixelXpert version which I named it AospXpert for Android 12+ AOSP roms. yes, this is not for the GoogleOS(which I call the Google Pixel device's stock rom). So if u want to use my mod, pls go to my project: https://github.com/dttzyjw0012/AospXpert. And do not reply in this issus, i know the PixelXpert team do not to want to be disturbed.

to PixelXpert team: i reply this because i can not @ this issus auther or participants in my issus: https://github.com/siavash79/PixelXpert/issues/980 , but there are just 10 issus i will reply just like this, so i wish this would not disturb you, thx.
