### ISSUE TITLE
Network Monitor: wrong speed measurement when using VPN

### ISSUE THREAD

**Issue by frak0d** [siavash79/PixelXpert#935]
normally the speed measurement is accurate, but if i use any vpn, the monitor shows speed 2-3x the actual speed.

i believe its Directly adding speeds for all network interfaces, but correct way would be to ignore tun (vpn) interfaces.

and since i use adguard, which creates an always on local vpn for ad filtering, network monitor always shows me wrong speed.

i also checked other vpn apps like proton vpn, they cause the same issue.

My Setup:
Motorola G64 (Almost stock Android 14)
Lsposed 1.10.1
PixelExpert 4.0.0

**Comment by EleoXDA** [comment]
Perfect! You even failed to acknowledge (and read it written in README file clean and wide) that THIS MOD IS ONLY FOR PIXEL DEVICES RUNNING ON STOCK PIXEL FIRMWARE. I don't know what kind of android knowledge you have since you are calling MOTOROLA's closed source idiotic ROM as `almost stock android 14`. Anyways. Next time read README file before installing a mod. I will add a script to brick devices that are not running stock pixel firmware. Maybe that will teach some a lesson.
